apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redakto-app-charite-ingress
  namespace: calgo-lab
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
    - host: "redakto-charite.demo.calgo-lab.de"
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: redakto-app-charite-service
                port:
                  name: api
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redakto-app-charite-service
                port:
                  name: ui
  tls:
    - hosts:
      - "redakto-charite.demo.calgo-lab.de"
      secretName: "redakto-charite-demo-subdomain-ingress"